name: Unit Tests

on:
  push:
    branches:
      - main  # Replace with your branch name if needed
  pull_request:
    branches:
      - main  # Replace with your branch name if needed

jobs:
  Jest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Run Tests
        run: |
          npm install 
          npm test